services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=sqlite:///./ALT_F4.db
    networks:
      - app-network
    #command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload  
    command: >
      sh -c "
        python app/seed.py &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Это важно! Не даем перезаписать node_modules из контейнера
    environment:
      - CHOKIDAR_USEPOLLING=true  # Для hot-reload в Docker
      - REACT_APP_API_URL=http://localhost:8000      
    stdin_open: true
    tty: true
    networks:
      - app-network
    depends_on:
      - backend
      
networks:
  app-network:
    driver: bridge
    
